# ============================================================================
# Vibe Kanban — Self-Hosted Deployment Config
#
# Only the first section is required. Everything else is optional and can be
# left empty — the server will simply disable those features.
#
# After editing, delete .env and re-run ./setup.sh to apply changes.
# ============================================================================


# ========================== REQUIRED ========================================

# Your machine's LAN IP address (setup.sh will auto-detect if left empty)
LAN_IP=192.168.1.177

# At least one login method must be configured:
#
# Option 1: GitHub OAuth
#   Create an OAuth app at https://github.com/settings/developers
#   Set the callback URL to: https://<LAN_IP>/v1/oauth/github/callback
GITHUB_OAUTH_CLIENT_ID=
GITHUB_OAUTH_CLIENT_SECRET=

# Option 2: Google OAuth
#   Create credentials at https://console.cloud.google.com/apis/credentials
#   Set the redirect URI to: https://<LAN_IP>/v1/oauth/google/callback
GOOGLE_OAUTH_CLIENT_ID=
GOOGLE_OAUTH_CLIENT_SECRET=

# Option 3: Local email/password (simplest — no external services needed)
#   Creates a bootstrap admin account on first start.
SELF_HOST_LOCAL_AUTH_EMAIL=admin@example.com
SELF_HOST_LOCAL_AUTH_PASSWORD=changeme


# ========================== NETWORK =========================================
# You probably don't need to change these unless you have port conflicts.

BIND_ADDR=0.0.0.0
HTTPS_PORT=443
RELAY_PORT=8443


# ========================== EVERYTHING BELOW IS OPTIONAL ====================
# Leave values empty to disable. The server works fine without any of these.
# ============================================================================


# --- Email notifications (Loops) -------------------------------------------
# Sign up at https://loops.so to get an API key.
# Without this, invites still work — you just share the link manually
# (use ./invite.sh to get pending invite links).
LOOPS_EMAIL_API_KEY=
LOOPS_INVITE_TEMPLATE_ID=
LOOPS_REVIEW_READY_TEMPLATE_ID=
LOOPS_REVIEW_FAILED_TEMPLATE_ID=
DIGEST_ENABLED=false

# --- GitHub App integration ------------------------------------------------
# Enables deeper GitHub integration (webhooks, automated actions).
# See https://docs.github.com/en/apps/creating-github-apps
GITHUB_APP_ID=
GITHUB_APP_PRIVATE_KEY=
GITHUB_APP_WEBHOOK_SECRET=
GITHUB_APP_SLUG=

# --- File attachments (Azure Blob Storage) ----------------------------------
# Enables file uploads on issues. Works with Azure Blob Storage or any
# S3-compatible service (e.g. MinIO) via the endpoint URL override.
AZURE_STORAGE_ACCOUNT_NAME=
AZURE_STORAGE_ACCOUNT_KEY=
AZURE_STORAGE_CONTAINER_NAME=issue-attachments
AZURE_STORAGE_ENDPOINT_URL=
AZURE_STORAGE_PUBLIC_ENDPOINT_URL=
AZURE_MANAGED_IDENTITY_CLIENT_ID=
AZURE_BLOB_PRESIGN_EXPIRY_SECS=

# --- Code review artifacts (Cloudflare R2) ----------------------------------
# Stores review output. Only needed if you use the review feature.
R2_ACCESS_KEY_ID=
R2_SECRET_ACCESS_KEY=
R2_REVIEW_ENDPOINT=
R2_REVIEW_BUCKET=
R2_PRESIGN_EXPIRY_SECS=
REVIEW_WORKER_BASE_URL=
REVIEW_DISABLED=false

# --- Billing (Stripe) ------------------------------------------------------
# Only relevant if you want to charge for team seats.
STRIPE_SECRET_KEY=
STRIPE_TEAM_SEAT_PRICE_ID=
STRIPE_WEBHOOK_SECRET=
STRIPE_FREE_SEAT_LIMIT=1

# --- Observability ----------------------------------------------------------
# Error tracking and analytics. Totally optional.
SENTRY_DSN_REMOTE=
POSTHOG_API_KEY=
POSTHOG_API_ENDPOINT=
APPLICATIONINSIGHTS_CONNECTION_STRING=
RUST_LOG=info,remote=info

# --- TLS certificate -------------------------------------------------------
# Controls the self-signed cert generated by setup.sh.
CERT_DAYS=1825
CERT_KEY_BITS=2048

# --- Source repo ------------------------------------------------------------
REPO_URL=https://github.com/BloopAI/vibe-kanban.git
REPO_DIR=vibekanban
