#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/config.sh"

echo "App URL:   $APP_URL"
echo "Relay URL: $RELAY_URL"

# --- Clone source repo ---
if [ ! -d "$REPO_DIR" ]; then
  echo "Cloning vibekanban..."
  git clone "$REPO_URL" "$REPO_DIR"
else
  echo "Updating vibekanban..."
  git -C "$REPO_DIR" pull --ff-only || true
fi

# --- Generate .env ---
if [ ! -f .env ]; then
  echo "Generating .env..."
  cat > .env <<EOF
# Generated by setup.sh — re-run ./setup.sh after editing config.sh
# Secrets
VIBEKANBAN_REMOTE_JWT_SECRET=$(openssl rand -base64 48)
ELECTRIC_ROLE_PASSWORD=$(openssl rand -base64 32)
DB_PASSWORD=$(openssl rand -base64 32)

# URLs
APP_URL=${APP_URL}
RELAY_URL=${RELAY_URL}

# Proxy
PROXY_ENABLED=${PROXY_ENABLED}
BIND_ADDR=${BIND_ADDR}
HTTPS_PORT=${HTTPS_PORT}
RELAY_PORT=${RELAY_PORT}

# Logging
RUST_LOG=${RUST_LOG}

# Auth — GitHub OAuth
GITHUB_OAUTH_CLIENT_ID=${GITHUB_OAUTH_CLIENT_ID}
GITHUB_OAUTH_CLIENT_SECRET=${GITHUB_OAUTH_CLIENT_SECRET}

# Auth — Google OAuth
GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}

# Auth — Local
SELF_HOST_LOCAL_AUTH_EMAIL=${SELF_HOST_LOCAL_AUTH_EMAIL}
SELF_HOST_LOCAL_AUTH_PASSWORD=${SELF_HOST_LOCAL_AUTH_PASSWORD}

# GitHub App
GITHUB_APP_ID=${GITHUB_APP_ID}
GITHUB_APP_PRIVATE_KEY=${GITHUB_APP_PRIVATE_KEY}
GITHUB_APP_WEBHOOK_SECRET=${GITHUB_APP_WEBHOOK_SECRET}
GITHUB_APP_SLUG=${GITHUB_APP_SLUG}

# Email — Loops
LOOPS_EMAIL_API_KEY=${LOOPS_EMAIL_API_KEY}
LOOPS_INVITE_TEMPLATE_ID=${LOOPS_INVITE_TEMPLATE_ID}
LOOPS_REVIEW_READY_TEMPLATE_ID=${LOOPS_REVIEW_READY_TEMPLATE_ID}
LOOPS_REVIEW_FAILED_TEMPLATE_ID=${LOOPS_REVIEW_FAILED_TEMPLATE_ID}
DIGEST_ENABLED=${DIGEST_ENABLED}

# Attachments — Azure Blob
AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
AZURE_STORAGE_ACCOUNT_KEY=${AZURE_STORAGE_ACCOUNT_KEY}
AZURE_STORAGE_CONTAINER_NAME=${AZURE_STORAGE_CONTAINER_NAME}
AZURE_STORAGE_ENDPOINT_URL=${AZURE_STORAGE_ENDPOINT_URL}
AZURE_STORAGE_PUBLIC_ENDPOINT_URL=${AZURE_STORAGE_PUBLIC_ENDPOINT_URL}
AZURE_MANAGED_IDENTITY_CLIENT_ID=${AZURE_MANAGED_IDENTITY_CLIENT_ID}
AZURE_BLOB_PRESIGN_EXPIRY_SECS=${AZURE_BLOB_PRESIGN_EXPIRY_SECS}

# Review — R2
R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
R2_REVIEW_ENDPOINT=${R2_REVIEW_ENDPOINT}
R2_REVIEW_BUCKET=${R2_REVIEW_BUCKET}
R2_PRESIGN_EXPIRY_SECS=${R2_PRESIGN_EXPIRY_SECS}

# Review worker
REVIEW_WORKER_BASE_URL=${REVIEW_WORKER_BASE_URL}
REVIEW_DISABLED=${REVIEW_DISABLED}

# Billing — Stripe
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_TEAM_SEAT_PRICE_ID=${STRIPE_TEAM_SEAT_PRICE_ID}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
STRIPE_FREE_SEAT_LIMIT=${STRIPE_FREE_SEAT_LIMIT}

# Observability
SENTRY_DSN_REMOTE=${SENTRY_DSN_REMOTE}
POSTHOG_API_KEY=${POSTHOG_API_KEY}
POSTHOG_API_ENDPOINT=${POSTHOG_API_ENDPOINT}
APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
EOF
  echo "Created .env"
else
  echo ".env already exists, skipping. Delete it and re-run to regenerate."
fi

# --- Generate self-signed cert (only when proxy is enabled) ---
if [ "${PROXY_ENABLED}" = "true" ]; then
  if [ ! -f selfsigned.crt ]; then
    # Extract host from APP_URL (strip scheme and port)
    HOST=$(echo "$APP_URL" | sed 's|https\?://||; s|:.*||')

    # Build SAN list starting with the primary host
    SANS=""
    for entry in $HOST ${CERT_EXTRA_SANS:-}; do
      if echo "$entry" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'; then
        SANS="${SANS:+${SANS},}IP:${entry}"
      else
        SANS="${SANS:+${SANS},}DNS:${entry}"
      fi
    done

    echo "Generating self-signed certificate (SANs: ${SANS})..."
    openssl req -x509 -newkey rsa:${CERT_KEY_BITS} -days ${CERT_DAYS} -nodes \
      -keyout selfsigned.key \
      -out selfsigned.crt \
      -subj "/CN=${HOST}" \
      -addext "subjectAltName=${SANS}" 2>/dev/null
  else
    echo "Certificate already exists, skipping."
  fi
fi

echo ""
echo "Done. Next steps:"
echo "  1. Edit config.sh if needed, delete .env, re-run ./setup.sh"
echo "  2. Run: ./up.sh"
echo "  3. Open ${APP_URL}"
